line-length = 120
target-version = "py310"

[lint]
ignore = ["E402", "SIM105", "SIM117", "SIM102", "UP045", "UP006", "UP007", "UP035"]

[lint.per-file-ignores]
"test_*.py" = ["E402", "F401", "I001"]
"scripts/test_*.py" = ["E402", "F401"]
