import asyncio
import time
import sys
import json
import subprocess
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.utils.logger import _log
from scripts.ingestion.role_filter import matches_target_role
from scripts.ingestion.us_filter import is_us_location
from scripts.database.db_utils import get_connection, insert_job, log_scraper_run

# Map of the protected "Big 5" job boards we need to bypass Cloudflare/Bot-protection for
PROTECTED_TARGETS = [
    {
        "name": "LinkedIn AI Jobs",
        "url": "https://www.linkedin.com/jobs/search/?keywords=AI%20Software%20Engineer&location=United%20States&f_TPR=r3600&position=1&pageNum=0",
        "source_ats": "linkedin"
    },
    {
        "name": "Indeed SWE",
        "url": "https://www.indeed.com/jobs?q=Software+Engineer&l=United+States&fromage=1",
        "source_ats": "indeed"
    },
    {
        "name": "Glassdoor Tech",
        "url": "https://www.glassdoor.com/Job/united-states-software-engineer-jobs-SRCH_IL.0,13_IN1_KO14,31.htm?fromAge=1",
        "source_ats": "glassdoor"
    }
]

def parse_openclaw_output(json_output_path: str) -> list[dict]:
    """Reads the JSON output generated by the OpenClaw CLI and parses jobs."""
    jobs = []
    try:
        with open(json_output_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        # The prompt instructed OpenClaw to return an array of objects
        if isinstance(data, list):
            for j in data:
                title = j.get("title", "")
                company = j.get("company", "Unknown")
                url = j.get("url", "")
                location = j.get("location", "Unknown United States")
                
                # Minimum viable job object
                if title and url:
                    jobs.append({
                        "title": title,
                        "company": company,
                        "location": location,
                        "url": url,
                        "date_posted": "", # Handled by 24hr filter implicitly from the URL query
                        "job_id": url.split("?")[0] # Best guess
                    })
    except Exception as e:
        _log(f"Failed to parse OpenClaw output: {e}", "ERROR")
        
    return jobs

async def run_openclaw_target(target: dict) -> list[dict]:
    """Runs a single target through the OpenClaw CLI headlessly using a dynamic YAML agent."""
    _log(f"Launching OpenClaw Agent for {target['name']}...")
    
    agent_file = PROJECT_ROOT / "data" / f"agent_{target['source_ats']}.yaml"
    output_file = PROJECT_ROOT / "data" / f"openclaw_{target['source_ats']}.json"
    
    # Generate the dynamic YAML configuration for OpenClaw
    yaml_config = f"""name: {target['source_ats']}_agent
description: Extract job listings from {target['name']}
provider:
  name: minimax
  model: MiniMax-M2.5
  base_url: https://api.minimax.io/v1
  temperature: 0.3
  max_tokens: 4096

system_prompt: |
  You are a web scraping assistant. Wait for the page to load fully.
  Scroll down to load more jobs if necessary. Extract the top 15 job listings visible.
  IMPORTANT: ONLY extract jobs that were posted in the LAST 1 HOUR. If a job says "2 hours ago" or "1d ago", ignore it.
  Return the data STRICTLY as a JSON array of objects with the keys:
  'title', 'company', 'location', and 'url'. Do not include any other text.
  If you cannot find listings matching the 1-hour criteria, return an empty array [].

tools:
  - name: browse_web
    description: Navigate to a URL and read page content
    parameters:
      url:
        type: string
        description: URL to navigate to
        default: "{target['url']}"

settings:
  timeout_seconds: 300
  max_retries: 2
  retry_delay_seconds: 5
  output_format: json
  output_path: "{str(output_file).replace(chr(92), '/')}"
"""

    # Write the temporary agent config
    with open(agent_file, "w", encoding="utf-8") as f:
        f.write(yaml_config)
    
    try:
        # Run the openclaw CLI command
        # Use a list instead of a shell string to prevent injection.
        # 'openclaw' must be on PATH; no shell expansion occurs.
        command = ["openclaw", "run", str(agent_file)]

        process = await asyncio.to_thread(
            subprocess.run,
            command,
            shell=False,
            capture_output=True,
            text=True,
            timeout=330
        )
        
        if process.returncode != 0:
            _log(f"OpenClaw failed for {target['name']}: {process.stderr}", "ERROR")
            return []
            
        _log(f"OpenClaw extraction finished for {target['name']}.")
        
        # Cleanup temp agent file
        try:
            agent_file.unlink(missing_ok=True)
        except Exception:
            pass
            
        return parse_openclaw_output(str(output_file))
        
    except subprocess.TimeoutExpired:
        _log(f"OpenClaw TIMEOUT for {target['name']} after 5 minutes.", "ERROR")
        return []


async def run_openclaw_scraper(extra_companies: list = None):
    """
    Micro-scraper exclusively for orchestrating the OpenClaw CLI against protected Cloudflare endpoints.
    Can also accept 'extra_companies' (e.g. Workday ATS links) that failed standard scraping due to bot protection.
    """
    start_time = time.time()
    _log(">>> Starting OpenClaw Anti-Bot Micro-Scraper")
    
    all_jobs = []
    errors = []
    
    # 1. Standard Targets
    targets = list(PROTECTED_TARGETS)
    
    # 2. Add extra companies (typically Workday ATS)
    if extra_companies:
        _log(f"Received {len(extra_companies)} extra companies for OpenClaw routing.")
        for c in extra_companies:
            if c.get("ats") == "workday" and "slug" in c:
                parts = c["slug"].split(":")
                if len(parts) == 3:
                    tenant, shard, site = parts
                    url = f"https://{tenant}.wd{shard}.myworkdayjobs.com/en-US/{site}"
                    targets.append({
                        "name": f"Workday_{c['company'].replace(' ', '')}",
                        "url": url,
                        "instructions": "Wait for the job listings grid to load. Extract all software engineering, data, AI, and product roles currently visible. Note the job title, location, and the link to the description page.",
                        "source_ats": "workday",
                        "company_override": c["company"]
                    })
    
    for target in targets:
        try:
            jobs = await run_openclaw_target(target)
            for j in jobs:
                 j["source_ats"] = target["source_ats"]
                 if "company_override" in target:
                     j["company"] = target["company_override"]
            all_jobs.extend(jobs)
        except Exception as e:
            errors.append(f"{target['name']}: {str(e)}")
            
    _log(f"Fetched {len(all_jobs)} total raw jobs using Browser Automation.")
    
    # Filtering Phase
    role_filtered = [j for j in all_jobs if matches_target_role(j["title"])]
    _log(f"Role filter: {len(role_filtered)}/{len(all_jobs)} matched target tech roles.")
    
    us_filtered = [j for j in role_filtered if is_us_location(j["location"])]
    _log(f"US filter: {len(us_filtered)}/{len(role_filtered)} in United States.")
    
    # Note: For LinkedIn we force `r3600` via URL. For others, the LLM prompt 
    # strictly filters for listings showing "last hour" / "minutes ago".
    time_filtered = us_filtered
    
    # Database injection + Deduplication
    conn = get_connection()
    new_jobs_inserted = 0
    try:
        for job in time_filtered:
            if insert_job(conn, job):
                new_jobs_inserted += 1
                
    except Exception as e:
        _log(f"Database insertion error: {str(e)}", "ERROR")
        errors.append(str(e))
        
    duration = round(time.time() - start_time, 2)
    err_str = "; ".join(errors) if errors else ""
    try:
        log_scraper_run(conn, "scrape_openclaw", len(PROTECTED_TARGETS), new_jobs_inserted, duration, err_str)
    finally:
        conn.close()
    
    _log(f">>> OpenClaw Scraper Complete. Found {new_jobs_inserted} brand new jobs out of {len(time_filtered)} candidates. (Took {duration}s)")

if __name__ == "__main__":
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(run_openclaw_scraper())
